language: node_js
node_js:
  - '10'
  - '12'
sudo: false
cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - yarn test

deploy:
  provider: npm
  email: ghedamat@gmail.com
  api_key:
    secure: MDGspGYSoGecqxePVz9c9MCuTA0L0NhNv1HaHzuLeq6/DTb4TqpIcgAx7tG3fnMOG8IvIv60J3fAD/GY6eYfrdWp0RwfrXbihsEM5VNVdeT4t++eV1bkWNk2CvmASyPCQt3nrchkkth+W2pV2NrZok+hFyvTOxIUdMzKgOEvPjE=
  on:
    tags: true
    repo: ember-cli-deploy/ember-cli-deploy-redis
